2018/11/21 14:18:59 [error] 6#6: *13 "/var/www/localhost/htdocs/default/index.php" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2018/11/21 14:18:59 [error] 6#6: *13 open() "/var/www/localhost/htdocs/default/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2018/11/21 14:19:17 [error] 6#6: *14 "/var/www/localhost/htdocs/default/index.php" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "10.42.0.207"
2018/11/21 14:19:17 [error] 6#6: *14 open() "/var/www/localhost/htdocs/default/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "10.42.0.207", referrer: "http://10.42.0.207/"
2018/11/21 14:19:21 [error] 6#6: *14 "/var/www/localhost/htdocs/default/index.php" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "10.42.0.207"
2018/11/30 14:25:24 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: local.orfeobackend.com, request: "POST /api/v1/login HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "local.orfeobackend.com"
2018/12/18 17:48:58 [error] 7#7: *1 "/var/www/localhost/htdocs/default/index.php" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 17:49:00 [error] 7#7: *1 open() "/var/www/localhost/htdocs/default/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "local.todocu.com", referrer: "http://local.todocu.com/"
2018/12/18 17:49:34 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "local.todocu.com"
2018/12/18 18:25:56 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 18:25:58 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 18:25:58 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 18:25:58 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 18:25:59 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/18 18:26:10 [error] 6#6: *1 directory index of "/var/www/localhost/htdocs/softwareAgil/frontTodocu/" is forbidden, client: 172.18.0.1, server: local.todocu.com, request: "GET / HTTP/1.1", host: "local.todocu.com"
2018/12/19 22:31:14 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: local.todocuback.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "local.todocuback.com"
2018/12/19 22:31:54 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: local.todocuback.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "local.todocuback.com"
2018/12/19 22:31:56 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: local.todocuback.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "local.todocuback.com"
2018/12/19 22:34:25 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:26 [error] 7#7: *6 open() "/var/www/localhost/htdocs/site/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: docker.local.com, request: "GET /favicon.ico HTTP/1.1", host: "docker.local.com", referrer: "http://docker.local.com/"
2018/12/19 22:34:27 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:28 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:28 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:28 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:28 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:29 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:29 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:29 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:34:29 [error] 7#7: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/19 22:42:23 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:48:17 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:48:18 [error] 6#6: *1 open() "/var/www/localhost/htdocs/site/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: docker.local.com, request: "GET /favicon.ico HTTP/1.1", host: "docker.local.com", referrer: "http://docker.local.com/"
2018/12/20 13:50:08 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:25 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:25 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:26 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:26 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:26 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:26 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:27 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:27 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:28 [error] 7#7: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:28 [error] 7#7: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 13:50:29 [error] 7#7: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:28 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:29 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:29 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:29 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:29 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:30 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:03:30 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:40 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:10:41 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:14:49 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:14:50 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 14:14:51 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2018/12/20 16:12:08 [error] 8#8: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: docker.local.com, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "docker.local.com"
2019/02/06 14:19:27 [error] 6#6: *1 "/var/www/localhost/htdocs/default/index.php" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2019/02/06 14:19:30 [error] 6#6: *1 open() "/var/www/localhost/htdocs/default/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
